#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# PolarisGate One-Command Deploy
# Usage:  bash scripts/deploy.sh
# Pipeline: 🏗️ BUILD → 🧪 TEST → 🚀 DEPLOY
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m' # No Color

log()  { echo -e "${CYAN}[deploy]${NC} $*"; }
ok()   { echo -e "${GREEN}[  ok ]${NC} $*"; }
warn() { echo -e "${YELLOW}[warn ]${NC} $*"; }
fail() { echo -e "${RED}[FAIL ]${NC} $*"; exit 1; }

# ═══════════════════════════════════════════════════════════════════════════
# 1. Prerequisites
# ═══════════════════════════════════════════════════════════════════════════
log "Checking prerequisites..."
command -v docker >/dev/null 2>&1 || fail "Docker is not installed"
command -v docker compose >/dev/null 2>&1 || fail "Docker Compose is not installed"
ok "Docker is available"

DOCKER_MEM=$(docker info --format '{{.MemTotal}}' 2>/dev/null || echo "0")
MIN_MEM=$((12 * 1024 * 1024 * 1024))  # 12 GB in bytes
if [ "$DOCKER_MEM" -lt "$MIN_MEM" ]; then
    warn "Docker memory is $((DOCKER_MEM / 1024 / 1024 / 1024)) GB — recommend at least 12 GB"
    warn "Increase in Docker Desktop → Settings → Resources → Memory"
else
    ok "Docker memory: $((DOCKER_MEM / 1024 / 1024 / 1024)) GB"
fi

# ═══════════════════════════════════════════════════════════════════════════
# 2. Generate .env if missing
# ═══════════════════════════════════════════════════════════════════════════
if [ ! -f .env ]; then
    log "Generating .env with secure random secrets..."
    DB_PASS=$(openssl rand -hex 32)
    REDIS_PASS=$(openssl rand -hex 32)
    JWT_SECRET=$(openssl rand -hex 64)
    ADMIN_PASS="PolarisGate@$(openssl rand -hex 4)"

    cat > .env <<EOF
# PolarisGate — Auto-generated by deploy.sh
DATABASE_URL=postgresql://polarisgate:${DB_PASS}@postgres:5432/polarisgate
READ_DATABASE_URL=postgresql://polarisgate:${DB_PASS}@postgres:5432/polarisgate
POSTGRES_USER=polarisgate
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=polarisgate

REDIS_PASSWORD=${REDIS_PASS}
REDIS_HOST=redis

JWT_SECRET=${JWT_SECRET}

OLLAMA_URL=http://ollama:11434
TOXIC_MODEL_NAME=llama3.2:1b

NEXT_PUBLIC_API_URL=http://localhost:8000

ENABLE_METRICS=true
OTEL_EXPORTER_OTLP_ENDPOINT=
OTEL_SERVICE_NAME=polarisgate
LOG_LEVEL=INFO
LOG_JSON_FORMAT=true

GUARDRAILS_URL=http://guardrails:8005
AIDA_URL=http://aida-bridge:8001
COLLECTOR_URL=http://collector:8006
BIAS_URL=http://bias-monitor:8007

RATE_LIMIT_DEFAULT=100
RATE_LIMIT_AUTH=30
RATE_LIMIT_GUARDRAILS=60

CORS_ORIGINS=http://localhost:3000
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7

DEPLOY_ADMIN_EMAIL=admin@polarisgate.ai
DEPLOY_ADMIN_PASSWORD=${ADMIN_PASS}
EOF
    ok "Generated .env with secure secrets"
    # Save admin password for final output
    echo "${ADMIN_PASS}" > /tmp/polarisgate_admin_pass.txt
else
    ok ".env already exists — using existing configuration"
    # Check for deploy admin credentials
    if grep -q "DEPLOY_ADMIN_PASSWORD" .env 2>/dev/null; then
        grep "DEPLOY_ADMIN_PASSWORD" .env | cut -d= -f2 > /tmp/polarisgate_admin_pass.txt 2>/dev/null || true
    fi
fi

# ═══════════════════════════════════════════════════════════════════════════
# 3. Build all images
# ═══════════════════════════════════════════════════════════════════════════
log "Building all Docker images (this may take 10-20 minutes on first run)..."
docker compose build --parallel 2>&1 | grep -E "(Built|ERROR|failed)" || true
ok "Build complete"

# ═══════════════════════════════════════════════════════════════════════════
# 4. 🧪 TEST — Accuracy Gates
# ═══════════════════════════════════════════════════════════════════════════
if [ "${SKIP_CHECKS:-0}" = "1" ]; then
    warn "TEST gates SKIPPED (SKIP_CHECKS=1)"
else
    log "Running accuracy gates..."
    if bash "${SCRIPT_DIR}/run_gates.sh"; then
        ok "All accuracy gates passed"
    else
        fail "Accuracy gates failed — deploy blocked.  To skip: SKIP_CHECKS=1 make deploy"
    fi
fi

# ═══════════════════════════════════════════════════════════════════════════
# 5. Pull external images
# ═══════════════════════════════════════════════════════════════════════════
log "Pulling external images..."
docker compose pull postgres redis ollama opa 2>&1 | tail -3
ok "External images pulled"

# ═══════════════════════════════════════════════════════════════════════════
# 5. Start infrastructure first
# ═══════════════════════════════════════════════════════════════════════════
log "Starting infrastructure services (PostgreSQL, Redis, Ollama)..."
docker compose up -d postgres redis ollama 2>&1 | grep -E "Started|Starting" || true

log "Waiting for infrastructure to be healthy..."
for i in $(seq 1 60); do
    POSTGRES_OK=$(docker compose ps postgres 2>/dev/null | grep -c "(healthy)" || echo "0")
    REDIS_OK=$(docker compose ps redis 2>/dev/null | grep -c "(healthy)" || echo "0")
    OLLAMA_OK=$(docker compose ps ollama 2>/dev/null | grep -c "(healthy)" || echo "0")
    if [ "$POSTGRES_OK" -ge 1 ] && [ "$REDIS_OK" -ge 1 ] && [ "$OLLAMA_OK" -ge 1 ]; then
        break
    fi
    echo -n "."
    sleep 2
done
echo ""
ok "Infrastructure services are healthy"

# ═══════════════════════════════════════════════════════════════════════════
# 6. Pull Ollama models
# ═══════════════════════════════════════════════════════════════════════════
log "Pulling Ollama models..."
docker compose exec -T ollama ollama pull llama3.2:1b 2>&1 | tail -3
ok "llama3.2:1b ready"

docker compose exec -T ollama ollama pull tinyllama 2>&1 | tail -3
ok "tinyllama ready"

# ═══════════════════════════════════════════════════════════════════════════
# 7. Start all remaining services
# ═══════════════════════════════════════════════════════════════════════════
log "Starting all services..."
docker compose up -d 2>&1 | grep -E "Started|Starting|Healthy" || true

log "Waiting for all services to be healthy..."
for i in $(seq 1 90); do
    UNHEALTHY=$(docker compose ps 2>/dev/null | grep -c "(unhealthy)" || echo "0")
    STARTING=$(docker compose ps 2>/dev/null | grep -c "(starting)" || echo "0")
    if [ "$UNHEALTHY" -eq 0 ] && [ "$STARTING" -eq 0 ]; then
        break
    fi
    echo -n "."
    sleep 3
done
echo ""

# ═══════════════════════════════════════════════════════════════════════════
# 8. Seed admin account
# ═══════════════════════════════════════════════════════════════════════════
log "Setting up admin account..."
sleep 5  # Wait for gateway to be ready

ADMIN_EMAIL="${DEPLOY_ADMIN_EMAIL:-admin@polarisgate.ai}"
ADMIN_PASSWORD="${DEPLOY_ADMIN_PASSWORD:-}"

if [ -z "$ADMIN_PASSWORD" ] && [ -f /tmp/polarisgate_admin_pass.txt ]; then
    ADMIN_PASSWORD=$(cat /tmp/polarisgate_admin_pass.txt)
fi
if [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD="PolarisGate@$(openssl rand -hex 4)"
fi

# Try to set up admin (idempotent — will 400 if already exists, which is fine)
SETUP_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://localhost:8000/auth/setup \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "username=${ADMIN_EMAIL}&password=${ADMIN_PASSWORD}" 2>/dev/null || echo "000")

if [ "$SETUP_RESPONSE" = "200" ]; then
    ok "Admin account created"
elif [ "$SETUP_RESPONSE" = "400" ]; then
    ok "Admin account already exists"
else
    warn "Admin setup returned HTTP ${SETUP_RESPONSE} — you may need to create manually"
fi

# Clean up temp file
rm -f /tmp/polarisgate_admin_pass.txt

# ═══════════════════════════════════════════════════════════════════════════
# 9. Final status
# ═══════════════════════════════════════════════════════════════════════════
SERVICE_COUNT=$(docker compose ps --format json 2>/dev/null | wc -l | tr -d ' ')
HEALTHY_COUNT=$(docker compose ps 2>/dev/null | grep -c "(healthy)" || echo "0")

echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║              PolarisGate is ready!                          ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Dashboard:${NC}  http://localhost:3000"
echo -e "  ${BOLD}API Docs:${NC}   http://localhost:8000/api/docs"
echo ""
echo -e "  ${BOLD}Email:${NC}      ${ADMIN_EMAIL}"
echo -e "  ${BOLD}Password:${NC}   ${ADMIN_PASSWORD}"
echo ""
echo -e "  ${BOLD}Services:${NC}   ${HEALTHY_COUNT}/${SERVICE_COUNT} healthy"
echo ""