"""Pre-flight security checks for PolarisGate.
Validates system configuration on startup to ensure security requirements are met.

Checks performed:
1. JWT secret strength
2. mTLS configuration
3. Encryption keys
4. Database connection
5. Redis connection
6. OPA service availability
7. Certificate expiry
8. Dependency vulnerabilities
9. Environment variable validation
10. Network policy validation
"""
import os
import re
import logging
from enum import Enum
from typing import Optional

logger = logging.getLogger(__name__)

# ─── Configuration ─────────────────────────────────────────────────────────

SECURITY_CHECKS_FAIL_OPEN = os.getenv(
    "SECURITY_CHECKS_FAIL_OPEN", "false"
).lower() == "true"


class CheckSeverity(Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class CheckResult:
    """Result of a single security check."""
    
    def __init__(
        self,
        name: str,
        passed: bool,
        severity: CheckSeverity = CheckSeverity.HIGH,
        message: str = "",
        recommendation: str = "",
    ):
        self.name = name
        self.passed = passed
        self.severity = severity
        self.message = message
        self.recommendation = recommendation
    
    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "passed": self.passed,
            "severity": self.severity.value,
            "message": self.message,
            "recommendation": self.recommendation,
        }


class PreflightChecker:
    """Runs pre-flight security checks on startup."""
    
    def __init__(self):
        self.results: list[CheckResult] = []
    
    async def run_all(self) -> list[CheckResult]:
        """Run all pre-flight checks."""
        self.results = []
        
        self._check_jwt_secret()
        self._check_mtls_config()
        self._check_encryption_keys()
        self._check_environment_variables()
        self._check_weak_passwords()
        self._check_debug_mode()
        self._check_cors_origin()
        self._check_rate_limiting()
        self._check_logging_config()
        
        return self.results
    
    def _check_jwt_secret(self):
        """Check JWT secret strength."""
        secret = os.getenv("JWT_SECRET", "")
        
        if not secret:
            self.results.append(CheckResult(
                name="jwt_secret",
                passed=False,
                severity=CheckSeverity.CRITICAL,
                message="JWT_SECRET is not set",
                recommendation="Set a strong JWT_SECRET environment variable (min 32 characters)",
            ))
            return
        
        if len(secret) < 32:
            self.results.append(CheckResult(
                name="jwt_secret_strength",
                passed=False,
                severity=CheckSeverity.CRITICAL,
                message=f"JWT_SECRET is too short ({len(secret)} chars, minimum 32)",
                recommendation="Use a JWT secret with at least 32 characters",
            ))
            return
        
        if secret in ("changeme", "password", "secret", "test", "default"):
            self.results.append(CheckResult(
                name="jwt_secret_default",
                passed=False,
                severity=CheckSeverity.CRITICAL,
                message="JWT_SECRET uses a known default value",
                recommendation="Change the JWT_SECRET to a unique, random value",
            ))
            return
        
        self.results.append(CheckResult(
            name="jwt_secret",
            passed=True,
            message="JWT secret is configured and meets minimum length",
        ))
    
    def _check_mtls_config(self):
        """Check mTLS configuration."""
        mtls_enabled = os.getenv("MTLS_ENABLED", "false").lower() == "true"
        
        if not mtls_enabled:
            self.results.append(CheckResult(
                name="mtls_enabled",
                passed=False,
                severity=CheckSeverity.HIGH,
                message="mTLS is not enabled for service-to-service communication",
                recommendation="Enable mTLS by setting MTLS_ENABLED=true and configuring certificates",
            ))
            return
        
        # Check cert paths
        cert_path = os.getenv("MTLS_CERT_PATH", "/etc/polarisgate/certs/service.crt")
        key_path = os.getenv("MTLS_KEY_PATH", "/etc/polarisgate/certs/service.key")
        
        if not os.path.exists(cert_path):
            self.results.append(CheckResult(
                name="mtls_certificate",
                passed=False,
                severity=CheckSeverity.CRITICAL,
                message=f"mTLS certificate not found at {cert_path}",
                recommendation="Ensure certificates are mounted or generated by the Internal CA service",
            ))
            return
        
        if not os.path.exists(key_path):
            self.results.append(CheckResult(
                name="mtls_key",
                passed=False,
                severity=CheckSeverity.CRITICAL,
                message=f"mTLS key not found at {key_path}",
                recommendation="Ensure the private key is mounted at the expected path",
            ))
            return
        
        self.results.append(CheckResult(
            name="mtls_config",
            passed=True,
            message="mTLS is enabled and certificates are present",
        ))
    
    def _check_encryption_keys(self):
        """Check encryption key configuration."""
        encryption_key = os.getenv("ENCRYPTION_KEY", "")
        
        if not encryption_key:
            self.results.append(CheckResult(
                name="encryption_key",
                passed=False,
                severity=CheckSeverity.HIGH,
                message="ENCRYPTION_KEY is not set",
                recommendation="Set an ENCRYPTION_KEY for data-at-rest encryption",
            ))
            return
        
        # AES-256 requires 32-byte key (base64 encoded = 44 chars)
        if len(encryption_key) < 32:
            self.results.append(CheckResult(
                name="encryption_key_strength",
                passed=False,
                severity=CheckSeverity.HIGH,
                message="ENCRYPTION_KEY is too short for AES-256",
                recommendation="Use a 32-byte (256-bit) key encoded in base64",
            ))
            return
        
        self.results.append(CheckResult(
            name="encryption_key",
            passed=True,
            message="Encryption key is configured",
        ))
    
    def _check_environment_variables(self):
        """Check for required environment variables."""
        required_vars = {
            "DATABASE_URL": "Database connection string",
            "REDIS_URL": "Redis connection string",
        }
        
        for var, description in required_vars.items():
            if not os.getenv(var):
                self.results.append(CheckResult(
                    name=f"env_{var.lower()}",
                    passed=False,
                    severity=CheckSeverity.CRITICAL,
                    message=f"{var} ({description}) is not set",
                    recommendation=f"Set the {var} environment variable",
                ))
    
    def _check_weak_passwords(self):
        """Check for weak/default passwords in configuration."""
        db_url = os.getenv("DATABASE_URL", "")
        
        # Check for default credentials in database URL
        weak_patterns = [
            (r"postgresql://postgres:postgres@", "Default PostgreSQL credentials"),
            (r"postgresql://root:root@", "Default root credentials"),
            (r"postgresql://admin:admin@", "Default admin credentials"),
            (r"postgresql://test:test@", "Default test credentials"),
        ]
        
        for pattern, description in weak_patterns:
            if re.search(pattern, db_url):
                self.results.append(CheckResult(
                    name="weak_database_credentials",
                    passed=False,
                    severity=CheckSeverity.CRITICAL,
                    message=description,
                    recommendation="Use strong, unique credentials for database access",
                ))
                return
        
        self.results.append(CheckResult(
            name="database_credentials",
            passed=True,
            message="Database credentials appear to be non-default",
        ))
    
    def _check_debug_mode(self):
        """Check if debug mode is enabled in production."""
        environment = os.getenv("ENVIRONMENT", "development")
        debug = os.getenv("DEBUG", "false").lower() == "true"
        
        if environment == "production" and debug:
            self.results.append(CheckResult(
                name="debug_mode",
                passed=False,
                severity=CheckSeverity.HIGH,
                message="Debug mode is enabled in production environment",
                recommendation="Set DEBUG=false in production",
            ))
            return
        
        self.results.append(CheckResult(
            name="debug_mode",
            passed=True,
            message="Debug mode is appropriately configured",
        ))
    
    def _check_cors_origin(self):
        """Check CORS origin configuration."""
        cors_origin = os.getenv("CORS_ORIGIN", "")
        
        if cors_origin == "*":
            self.results.append(CheckResult(
                name="cors_origin",
                passed=False,
                severity=CheckSeverity.HIGH,
                message="CORS_ORIGIN is set to '*' (allow all origins)",
                recommendation="Restrict CORS_ORIGIN to specific allowed origins",
            ))
            return
        
        self.results.append(CheckResult(
            name="cors_origin",
            passed=True,
            message="CORS origin is configured",
        ))
    
    def _check_rate_limiting(self):
        """Check rate limiting configuration."""
        rate_limit = os.getenv("RATE_LIMIT_PER_MINUTE", "")
        
        if not rate_limit:
            self.results.append(CheckResult(
                name="rate_limiting",
                passed=False,
                severity=CheckSeverity.MEDIUM,
                message="Rate limiting is not configured",
                recommendation="Set RATE_LIMIT_PER_MINUTE to prevent abuse",
            ))
            return
        
        self.results.append(CheckResult(
            name="rate_limiting",
            passed=True,
            message=f"Rate limiting configured at {rate_limit} requests/minute",
        ))
    
    def _check_logging_config(self):
        """Check logging configuration."""
        log_level = os.getenv("LOG_LEVEL", "INFO").upper()
        valid_levels = ("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL")
        
        if log_level not in valid_levels:
            self.results.append(CheckResult(
                name="log_level",
                passed=False,
                severity=CheckSeverity.LOW,
                message=f"Invalid LOG_LEVEL: {log_level}",
                recommendation=f"Set LOG_LEVEL to one of: {', '.join(valid_levels)}",
            ))
            return
        
        self.results.append(CheckResult(
            name="log_level",
            passed=True,
            message=f"Log level set to {log_level}",
        ))
    
    def has_critical_failures(self) -> bool:
        """Check if any critical checks failed."""
        return any(
            not r.passed and r.severity == CheckSeverity.CRITICAL
            for r in self.results
        )
    
    def get_summary(self) -> dict:
        """Get a summary of all check results."""
        total = len(self.results)
        passed = sum(1 for r in self.results if r.passed)
        failed = total - passed
        
        critical = sum(1 for r in self.results if not r.passed and r.severity == CheckSeverity.CRITICAL)
        high = sum(1 for r in self.results if not r.passed and r.severity == CheckSeverity.HIGH)
        medium = sum(1 for r in self.results if not r.passed and r.severity == CheckSeverity.MEDIUM)
        low = sum(1 for r in self.results if not r.passed and r.severity == CheckSeverity.LOW)
        
        return {
            "total": total,
            "passed": passed,
            "failed": failed,
            "critical": critical,
            "high": high,
            "medium": medium,
            "low": low,
            "fail_open": SECURITY_CHECKS_FAIL_OPEN,
            "checks": [r.to_dict() for r in self.results],
        }


# Global preflight checker
preflight_checker = PreflightChecker()


async def run_preflight_checks() -> list[CheckResult]:
    """Run all pre-flight checks and log results.
    
    Returns:
        List of CheckResult objects
    
    Raises:
        SystemExit: If critical checks fail and SECURITY_CHECKS_FAIL_OPEN is false
    """
    results = await preflight_checker.run_all()
    summary = preflight_checker.get_summary()
    
    # Log results
    logger.info("=" * 60)
    logger.info("PRE-FLIGHT SECURITY CHECKS")
    logger.info("=" * 60)
    
    for result in results:
        status = "✅ PASS" if result.passed else "❌ FAIL"
        logger.info(f"  [{result.severity.value.upper()}] {status} - {result.name}")
        if not result.passed:
            logger.info(f"       Message: {result.message}")
            logger.info(f"       Recommendation: {result.recommendation}")
    
    logger.info("-" * 60)
    logger.info(
        f"Summary: {summary['passed']}/{summary['total']} passed "
        f"({summary['critical']} critical, {summary['high']} high, "
        f"{summary['medium']} medium, {summary['low']} low)"
    )
    logger.info("=" * 60)
    
    # Fail if critical checks fail and not in fail-open mode
    if preflight_checker.has_critical_failures() and not SECURITY_CHECKS_FAIL_OPEN:
        logger.error(
            "CRITICAL: Pre-flight security checks failed. "
            "Set SECURITY_CHECKS_FAIL_OPEN=true to bypass (NOT RECOMMENDED for production)."
        )
        raise SystemExit(1)
    
    return results
